### ISSUE TITLE
ctx.args is broken

### ISSUE THREAD

**Issue by qbjl** [meower-community/MeowerBot.js#42]
**Describe the bug**
ctx.args only returns the @ of the bot.

**To Reproduce**
1. Make a bot that returns "ctx.args" into the console on command
2. Run bot
3. Send command to bot

**Expected behavior**
[ 'help', ... ], got [ '@bot' ]

**Comment by showierdata9978** [comment]
please don't assign me on mb.js stuff

**Comment by mdwalters** [comment]
> please don't assign me on mb.js stuff

ok bud
